language: android
jdk: oraclejdk8
sudo: required

env:
  global:
    - ANDROID_API_LEVEL=28
    - ANDROID_EMULATOR_LEVEL=18
    - ANDROID_BUILD_TOOLS_VERSION=28.0.0
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis

android:
  components:
    - toolssudo gem install travis
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - android-$ANDROID_EMULATOR_LEVEL
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-$ANDROID_ABI-google-apis-$ANDROID_EMULATOR_LEVEL
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_script:
  - chmod +x gradlew
  - export ANDROID_HOME=/Users/rit/Library/Android/sdk
  - export PATH=$PATH:$ANDROID_HOME/tools/bin

stages:
  - build

buildDebug:
  stage: build
  script:
    - ./gradlew assembleDebug